/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type RichTextBlock = {
  _type: "richTextBlock";
  eyebrow?: string;
  title?: string;
  content?: PortableContent;
  width?: "narrow" | "standard";
  background?: "plain" | "light" | "brand" | "dark";
  spacing?: "compact" | "standard" | "tall";
  textSize?: "standard" | "large";
  sectionId?: string;
};

export type FaqBlock = {
  _type: "faqBlock";
  title?: string;
  items?: Array<{
    question?: string;
    answer?: string;
    _key: string;
  }>;
  background?: "plain" | "light" | "brand" | "dark";
  spacing?: "compact" | "standard" | "tall";
  width?: "narrow" | "standard" | "wide";
  textAlign?: "left" | "center" | "right";
  sectionId?: string;
};

export type LogoCloudBlock = {
  _type: "logoCloudBlock";
  title?: string;
  logos?: Array<{
    name?: string;
    image?: ImageWithAlt;
    url?: string;
    _key: string;
  }>;
  background?: "plain" | "light" | "brand" | "dark";
  spacing?: "compact" | "standard" | "tall";
  width?: "narrow" | "standard" | "wide";
  textAlign?: "left" | "center" | "right";
  sectionId?: string;
};

export type TestimonialBlock = {
  _type: "testimonialBlock";
  quote?: string;
  avatar?: ImageWithAlt;
  name?: string;
  role?: string;
  background?: "plain" | "light" | "brand" | "dark";
  spacing?: "compact" | "standard" | "tall";
  width?: "narrow" | "standard" | "wide";
  textAlign?: "left" | "center" | "right";
  sectionId?: string;
};

export type FullWidthMediaBlock = {
  _type: "fullWidthMediaBlock";
  eyebrow?: string;
  title?: string;
  body?: string;
  image?: ImageWithAlt;
  action?: Link;
  background?: "plain" | "light" | "brand" | "dark";
  spacing?: "compact" | "standard" | "tall";
  width?: "narrow" | "standard" | "wide";
  textAlign?: "left" | "center" | "right";
  sectionId?: string;
};

export type GalleryBlock = {
  _type: "galleryBlock";
  eyebrow?: string;
  title?: string;
  body?: string;
  images?: Array<
    {
      _key: string;
    } & ImageWithAlt
  >;
  background?: "plain" | "light" | "brand" | "dark";
  spacing?: "compact" | "standard" | "tall";
  width?: "narrow" | "standard" | "wide";
  textAlign?: "left" | "center" | "right";
  columns?: "2" | "3" | "4";
  imageRatio?: "square" | "landscape" | "portrait" | "wide";
  sectionId?: string;
};

export type ImageTextBlock = {
  _type: "imageTextBlock";
  eyebrow?: string;
  title?: string;
  body?: string;
  image?: ImageWithAlt;
  action?: Link;
  background?: "plain" | "light" | "brand" | "dark";
  spacing?: "compact" | "standard" | "tall";
  width?: "narrow" | "standard" | "wide";
  textAlign?: "left" | "center" | "right";
  verticalAlign?: "top" | "center" | "bottom";
  imageRatio?: "square" | "landscape" | "portrait" | "wide";
  imageShape?: "square" | "rounded" | "soft";
  imagePosition?: "left" | "right" | "alternate";
  sectionId?: string;
};

export type FeatureGridBlock = {
  _type: "featureGridBlock";
  eyebrow?: string;
  title?: string;
  body?: string;
  features?: Array<{
    title?: string;
    body?: string;
    image?: ImageWithAlt;
    _key: string;
  }>;
  background?: "plain" | "light" | "brand" | "dark";
  spacing?: "compact" | "standard" | "tall";
  width?: "narrow" | "standard" | "wide";
  textAlign?: "left" | "center" | "right";
  columns?: "2" | "3" | "4";
  cardStyle?: "plain" | "bordered" | "elevated";
  sectionId?: string;
};

export type CtaBlock = {
  _type: "ctaBlock";
  eyebrow?: string;
  title?: string;
  body?: string;
  primaryAction?: Link;
  secondaryAction?: Link;
  background?: "plain" | "light" | "brand" | "dark";
  spacing?: "compact" | "standard" | "tall";
  width?: "narrow" | "standard" | "wide";
  textAlign?: "left" | "center" | "right";
  sectionId?: string;
};

export type HeroBlock = {
  _type: "heroBlock";
  eyebrow?: string;
  title?: string;
  body?: string;
  image?: ImageWithAlt;
  cta?: Link;
  layout?: "textOnly" | "imageRight" | "imageLeft" | "backgroundImage";
  textAlign?: "left" | "center" | "right";
  verticalAlign?: "top" | "center" | "bottom";
  typographyScale?: "standard" | "large" | "editorial";
  backgroundStyle?: "dark" | "light" | "brand" | "gradient";
  verticalSpacing?: "compact" | "standard" | "tall" | "fullViewport";
  sectionId?: string;
};

export type PageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "page";
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type PortableContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<
        | {
            href?: string;
            openInNewTab?: boolean;
            _type: "externalLink";
            _key: string;
          }
        | {
            page?: PageReference;
            openInNewTab?: boolean;
            _type: "internalLink";
            _key: string;
          }
      >;
      level?: number;
      _type: "block";
      _key: string;
    }
  | ({
      _key: string;
    } & ImageWithAlt)
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      caption?: string;
      width?: "narrow" | "standard" | "full";
      align?: "left" | "center" | "right";
      shape?: "square" | "rounded" | "soft";
      _type: "portableImage";
      _key: string;
    }
  | {
      tone?: "note" | "tip" | "warning";
      title?: string;
      body?: string;
      _type: "callout";
      _key: string;
    }
  | {
      action?: Link;
      variant?: "primary" | "secondary";
      _type: "contentAction";
      _key: string;
    }
  | {
      label?: string;
      _type: "divider";
      _key: string;
    }
  | {
      quote?: string;
      attribution?: string;
      _type: "pullQuote";
      _key: string;
    }
>;

export type ImageWithAlt = {
  _type: "imageWithAlt";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  caption?: string;
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  noIndex?: boolean;
};

export type Link = {
  _type: "link";
  label?: string;
  linkType?: "internal" | "external";
  page?: PageReference;
  href?: string;
  openInNewTab?: boolean;
  variant?: "primary" | "secondary" | "inverse";
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  logoText?: string;
  copyrightStartYear?: number;
  primaryNavigation?: Array<
    {
      _key: string;
    } & Link
  >;
  footerTagline?: string;
  footerNavigation?: Array<
    {
      _key: string;
    } & Link
  >;
  footerMenus?: Array<{
    title?: string;
    links?: Array<
      {
        _key: string;
      } & Link
    >;
    _key: string;
  }>;
  footerContact?: {
    email?: string;
    phone?: string;
    address?: string;
  };
  socialLinks?: Array<
    {
      _key: string;
    } & Link
  >;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  seo?: Seo;
  blocks?: Array<
    | ({
        _key: string;
      } & HeroBlock)
    | ({
        _key: string;
      } & CtaBlock)
    | ({
        _key: string;
      } & FeatureGridBlock)
    | ({
        _key: string;
      } & ImageTextBlock)
    | ({
        _key: string;
      } & GalleryBlock)
    | ({
        _key: string;
      } & FullWidthMediaBlock)
    | ({
        _key: string;
      } & TestimonialBlock)
    | ({
        _key: string;
      } & LogoCloudBlock)
    | ({
        _key: string;
      } & FaqBlock)
    | ({
        _key: string;
      } & RichTextBlock)
  >;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | RichTextBlock
  | FaqBlock
  | LogoCloudBlock
  | TestimonialBlock
  | FullWidthMediaBlock
  | GalleryBlock
  | ImageTextBlock
  | FeatureGridBlock
  | CtaBlock
  | HeroBlock
  | PageReference
  | SanityImageAssetReference
  | PortableContent
  | ImageWithAlt
  | Seo
  | Link
  | SiteSettings
  | Page
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;
